[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "BANKSY_py"
authors = [{name = "Nigel Chou", email = "nigel_chou@gis.a-star.edu.sg"}, {name = "Yue Yifei", email = "yueyifei@u.nus.edu"}]
dynamic = ["version", "description"]
